const songs = [
  "Src/Assets/Music/5 Seconds of Summer/Boyband - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Chest - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Close As Strangers - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Everyone\u2019s A Star! - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Evolve - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Ghost - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/I'll Find You - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/I'm_Scared_I\u2019ll_Never_Sleep_Again_5_Seconds_of_Summer_320.mp3",
  "Src/Assets/Music/5 Seconds of Summer/Jawbreaker - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/NOT OK - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/No. 1 Obsession - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Out Of My Limit - 5 Seconds of Summer (320) (9).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Out Of My Limit - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Sick of Myself - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Start Over - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Telephone Busy - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/The Rocks - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/Wishful Dreaming - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/5 Seconds of Summer/istillfeelthesame - 5 Seconds of Summer (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/obsessed - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/scared of my guitar - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (10).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (11).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (12).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (13).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (2).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (3).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (4).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (5).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (6).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (7).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (8).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320) (9).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/so american - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/GUTS/stranger - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/cigarette smoke - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/drop dead - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/expectations - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/honeybee - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/less - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/maggots for brains - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/my way - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/purple - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/stupid song - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/the cure - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/u + me = 3 - Olivia Rodrigo (320).mp3",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/what\u2019s wrong with me - Olivia Rodrigo  Robert Smith (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/Don\u2019t_Worry_I\u2019ll_Make_You_Worry_Sabrina_Carpenter_320.mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/House Tour - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/Manchild - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/My Man on Willpower - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/Nobody\u2019s Son - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/Sugar Talking - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/We_Almost_Broke_Up_Again_Last_Night_Sabrina_Carpenter_320.mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Don\u2019t Smile - Sabrina Carpenter (320) (2).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Don\u2019t Smile - Sabrina Carpenter (320) (3).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Don\u2019t Smile - Sabrina Carpenter (320) (4).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Don\u2019t Smile - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Espresso - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Juno- Sabrina Carpenter (320) (3).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Please Please Please- Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/Taste - Sabrina Carpenter (320).mp3",
  "Src/Assets/Music/Why Dont we/Fallin\u2019 (Adrenaline) - Why Don't We (320).mp3",
  "Src/Assets/Music/sombr/12 to 12 - sombr (320).mp3",
  "Src/Assets/Music/sombr/Homewrecker - sombr (320).mp3",
  "Src/Assets/Music/sombr/My Body Isn't Ready - sombr (320).mp3",
  "Src/Assets/Music/sombr/back to friends - sombr (320).mp3",
  "Src/Assets/Music/sombr/come closer - sombr (320).mp3",
  "Src/Assets/Music/sombr/do i ever cross your mind - sombr (320).mp3",
  "Src/Assets/Music/sombr/perfume - sombr (320).mp3",
  "Src/Assets/Music/sombr/undressed - sombr (320).mp3",
  "Src/Assets/Music/sombr/we never dated - sombr (320).mp3",
  "Src/Assets/Music/sombr/weak - sombr (320).mp3"
];

const COVER_MAP = {
  "Src/Assets/Music/5 Seconds of Summer": "Src/Assets/Music/5 Seconds of Summer/images.jpeg",
  "Src/Assets/Music/Olivia Rodrigo/GUTS": "Src/Assets/Music/Olivia Rodrigo/GUTS/images.jpeg",
  "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love": "Src/Assets/Music/Olivia Rodrigo/You seem pretty sad for a girl so in love/Olivia_Rodrigo_-_You_Seem_Pretty_Sad_for_a_Girl_So_in_Love.png",
  "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends": "Src/Assets/Music/Sabrina Carpenter/Man's bestfriends/download.jpeg",
  "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet": "Src/Assets/Music/Sabrina Carpenter/Short'n and sweet/images.jpeg",
  "Src/Assets/Music/Why Dont we": "Src/Assets/Music/Why Dont we/images (1).jpeg",
  "Src/Assets/Music/sombr": "Src/Assets/Music/sombr/hbz020126playlist-003-6978de6eb962b.avif"
};

const FALLBACK_SONGS = [
  {"title": "Blinding Lights", "artist": "The Weeknd", "album": "After Hours", "genre": "Synthwave", "year": 2020},
  {"title": "Bohemian Rhapsody", "artist": "Queen", "album": "A Night at the Opera", "genre": "Rock", "year": 1975},
  {"title": "Shape of You", "artist": "Ed Sheeran", "album": "\u00f7", "genre": "Pop", "year": 2017},
  {"title": "Starboy", "artist": "The Weeknd", "album": "Starboy", "genre": "R&B", "year": 2016},
  {"title": "Bad Guy", "artist": "Billie Eilish", "album": "WHEN WE ALL FALL ASLEEP", "genre": "Pop", "year": 2019},
  {"title": "Levitating", "artist": "Dua Lipa", "album": "Future Nostalgia", "genre": "Dance Pop", "year": 2020},
  {"title": "Save Your Tears", "artist": "The Weeknd", "album": "After Hours", "genre": "Synthwave", "year": 2020},
  {"title": "Watermelon Sugar", "artist": "Harry Styles", "album": "Fine Line", "genre": "Pop", "year": 2019},
  {"title": "Don't Start Now", "artist": "Dua Lipa", "album": "Future Nostalgia", "genre": "Dance Pop", "year": 2019},
  {"title": "Circles", "artist": "Post Malone", "album": "Hollywood's Bleeding", "genre": "Pop Rock", "year": 2019},
  {"title": "Dynamite", "artist": "BTS", "album": "Dynamite", "genre": "K-Pop", "year": 2020},
  {"title": "Peaches", "artist": "Justin Bieber", "album": "Justice", "genre": "Pop", "year": 2021},
  {"title": "Stay", "artist": "The Kid LAROI & Justin Bieber", "album": "F*CK LOVE 3", "genre": "Pop", "year": 2021},
  {"title": "Good 4 U", "artist": "Olivia Rodrigo", "album": "SOUR", "genre": "Pop Rock", "year": 2021},
  {"title": "Montero", "artist": "Lil Nas X", "album": "MONTERO", "genre": "Hip Hop", "year": 2021}
];
